# Generated by Django 4.2.2 on 2023-07-06 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_fantasy_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='postion',
            new_name='position',
        ),
    ]
